apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxroute
  namespace: fluxroute
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fluxroute
  template:
    metadata:
      labels:
        app: fluxroute
    spec:
      containers:
        - name: router
          image: fluxroute:dev
          imagePullPolicy: IfNotPresent
          args: ["serve"]
          envFrom:
            - configMapRef:
                name: fluxroute-config
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 2112
              name: metrics
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
