apiVersion: v1
kind: Service
metadata:
  name: fluxroute
  namespace: fluxroute
spec:
  selector:
    app: fluxroute
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: metrics
      port: 2112
      targetPort: metrics
